language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 #- 5.4
 #- 5.5
 - 5.6
 - 7.0

matrix:
 fast_finish: true
 exclude:
    # MySQL - we do not use the database to store data
    - env: DB=mysqli   PHPUNIT=true    INSTALL=false   CITEST=false
      php: 5.6
    - env: DB=mysqli   PHPUNIT=true    INSTALL=false   CITEST=false
      php: 7.0

env:
 global:
  - MOODLE_BRANCH=master
 matrix:
  - DB=mysqli

install:
  - composer install
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit
 